# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Uploaded Fairy
tab_title: A Four Frame Novel #This text shows up on the browser tab
email:
description: In a world where French-America and Japanese-America locked in civil war, an apprentice executioner torn between love and justice. We explore what led up to the civil unrest, to the aftermath eighty years in the future when America speaks Fraponic.
url: "https://lwflouisa.github.io/UploadedFairy/" # the base hostname & protocol for your site

# Comic Social Media
# twitter_username: http://twitter.com/FlouisaLW
# patreon_username: Sarah

# Author Social Media
author_twitter_username: ToDiaspora
# author_tumblr_username:
# author_patreon_username:

# Build settings
markdown: kramdown
theme: minima
